server:
  port: 8888
  tomcat:
      uri-encoding: UTF-8
spring:
  aop:
    auto: true
    proxy-target-class: true
  application:
    name: spring-boot-demo
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

